import Head from 'next/head'
import Classes from '../styles/main.module.css'
import { useState,useEffect } from 'react'

export default function Home() {
  const [score,setScore] = useState(0);
  const [gameOver,setGameOver] = useState(false)

  useEffect(() => {
     var ball = document.querySelector("b")
     var ball2 = document.querySelector("span")
     var ball3 = document.querySelector("p")
     var scoreListener = document.querySelector("strong")
     var score = 0;
    

    setTimeout(function(){document.getElementById("ball2").style.display="block"},10000);
    setTimeout(function(){document.getElementById("ball3").style.display="block"},15000);

    ball.addEventListener("mouseover", gameover);
    ball2.addEventListener("mouseover", gameover);
    ball3.addEventListener("mouseover", gameover);
   
    scoreListener.addEventListener("mouseover", scoreUp);
    
    function gameover(){
      setGameOver(true)
    }

    function scoreUp(){
      score += 1;
      document.getElementById("score").innerHTML = `${score}`
      setScore(score);
    }
  },[gameOver])
  
  if(gameOver === true){
    return (
    <div className={Classes.gameover}>
      <b>game over</b>
      <p>your score: {score}</p>
      <button onClick={() => {setGameOver(false)}}>play again</button>
      <b id='ball2'></b>
      <span></span>
    <strong id='ball3'></strong>
    </div>
    )
  }else{
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  <main className={Classes.main}>
  <div className={Classes.box}>
    <label id='score'>0</label>
    <b></b>
    <span style={{display:"none"}} id='ball2'></span>
    <p style={{display:"none"}} id='ball3'></p>
    <strong></strong>
    </div>
  </main>
      </div>
    )
  }
  
}